// Dashboard JavaScript for GSoC Student Dashboard

// Load configuration
async function loadConfig() {
    try {
        const response = await fetch('config.json');
        if (!response.ok) {
            throw new Error('Config file not found');
        }
        return await response.json();
    } catch (error) {
        console.error('Error loading config:', error);
        return getDefaultConfig();
    }
}

// Default configuration
function getDefaultConfig() {
    return {
        student: {
            name: "GSoC Student",
            bio: "Google Summer of Code Contributor",
            avatar: "https://via.placeholder.com/120",
            github: "",
            email: "",
            blog: "",
            linkedin: ""
        },
        project: {
            title: "My GSoC Project",
            description: "Working on an amazing open-source project through Google Summer of Code",
            organization: "Open Source Organization",
            timeline: "May 2024 - August 2024"
        },
        slack: {
            workspaceUrl: "",
            channels: []
        },
        mentors: [
            {
                name: "Mentor Name",
                email: "",
                avatar: "https://via.placeholder.com/80",
                role: "Lead Mentor"
            }
        ]
    };
}

// Helper to extract owner and repo from URL
function getRepoDetails(url) {
    if (!url) return null;
    try {
        const urlObj = new URL(url);
        const path = urlObj.pathname.replace(/^\/|\/$/g, '');
        const parts = path.split('/');
        if (parts.length >= 2) {
            return { owner: parts[0], repo: parts[1] };
        }
    } catch (e) {
        console.error("Invalid repo URL", e);
    }
    return null;
}

// Helper to extract username from URL
function getUsername(url) {
    if (!url) return null;
    try {
        const urlObj = new URL(url);
        const path = urlObj.pathname.replace(/^\/|\/$/g, '');
        const parts = path.split('/');
        if (parts.length >= 1) {
            return parts[0];
        }
    } catch (e) {
        console.error("Invalid github URL", e);
    }
    return null;
}

// Fetch GitHub data dynamically (supports multiple repos)
async function loadGitHubData(config) {
    // Try to fetch static data first (generated by CI/CD)
    try {
        const response = await fetch('data/github-contributions.json');
        if (response.ok) {
            const data = await response.json();
            // Check if data is not stale (optional, e.g. > 24h old)
            // For now, just return it
            return data;
        }
    } catch (e) {
        console.log('Static GitHub data not found, falling back to API');
    }

    const username = getUsername(config.student.github);

    // Normalize repositories list: handle array or single string (legacy)
    let repositories = [];
    if (config.project.repositories && Array.isArray(config.project.repositories)) {
        repositories = config.project.repositories;
    } else if (config.project.repository) {
        repositories = [config.project.repository];
    }

    if (repositories.length === 0 || !username) {
        console.warn("Repositories list or student GitHub URL missing/invalid in config.");
        return {
            stats: { commits: 0, pullRequests: 0, issues: 0, reviews: 0 },
            contributions: []
        };
    }

    const sixMonthsAgo = new Date();
    sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);
    const dateStr = sixMonthsAgo.toISOString().split('T')[0]; // YYYY-MM-DD

    let totalStats = { commits: 0, pullRequests: 0, issues: 0, reviews: 0 };
    let allContributions = [];

    // Process all repositories in parallel
    const promises = repositories.map(async (repoUrl) => {
        const repoDetails = getRepoDetails(repoUrl);
        if (!repoDetails) return;

        const { owner, repo } = repoDetails;

        try {
            // Fetch Pull Requests (Only merged)
            const prQuery = `repo:${owner}/${repo} is:pr is:merged author:${username} created:>${dateStr}`;
            const prResponse = await fetch(`https://api.github.com/search/issues?q=${encodeURIComponent(prQuery)}`);
            const prData = await prResponse.json();
            const prCount = prData.total_count || 0;

            // Fetch Issues
            const issueQuery = `repo:${owner}/${repo} is:issue author:${username} created:>${dateStr}`;
            const issueResponse = await fetch(`https://api.github.com/search/issues?q=${encodeURIComponent(issueQuery)}`);
            const issueData = await issueResponse.json();
            const issueCount = issueData.total_count || 0;

            // Fetch Reviews (Exclude own PRs)
            const reviewQuery = `repo:${owner}/${repo} is:pr reviewed-by:${username} -author:${username} created:>${dateStr}`;
            const reviewResponse = await fetch(`https://api.github.com/search/issues?q=${encodeURIComponent(reviewQuery)}`);
            const reviewData = await reviewResponse.json();
            const reviewCount = reviewData.total_count || 0;

            // Fetch Commits - Use List API per repo (more reliable than search for stats)
            let commitCount = 0;
            const commitResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/commits?author=${username}&since=${sixMonthsAgo.toISOString()}&per_page=1`);

            const linkHeader = commitResponse.headers.get('link');
            if (linkHeader) {
                const match = linkHeader.match(/&page=(\d+)>; rel="last"/);
                if (match) {
                    commitCount = parseInt(match[1], 10);
                } else {
                    // Single page result
                    const data = await commitResponse.json();
                    commitCount = Array.isArray(data) ? data.length : 0;
                }
            } else {
                if (commitResponse.ok) {
                    const data = await commitResponse.json();
                    if (Array.isArray(data)) commitCount = data.length;
                }
            }

            // Collect contributions
            if (prData.items && prData.items.length > 0) {
                const recentPRs = prData.items.slice(0, 5).map(item => ({
                    title: item.title,
                    description: `Pull Request #${item.number} in ${owner}/${repo}`,
                    date: item.created_at,
                    url: item.html_url,
                    timestamp: new Date(item.created_at).getTime()
                }));
                allContributions.push(...recentPRs);
            }

            // Update totals (safely)
            totalStats.commits += commitCount;
            totalStats.pullRequests += prCount;
            totalStats.issues += issueCount;
            totalStats.reviews += reviewCount;

        } catch (error) {
            console.error(`Error fetching data for ${owner}/${repo}:`, error);
        }
    });

    await Promise.all(promises);

    // Sort contributions by date desc and take top 5
    const sortedContributions = allContributions.sort((a, b) => b.timestamp - a.timestamp).slice(0, 5);
    // Remove temporary timestamp
    // const finalContributions = sortedContributions.map(({timestamp, ...rest}) => rest);

    return {
        stats: totalStats,
        contributions: sortedContributions
    };
}

// Load blog posts
async function loadBlogPosts() {
    try {
        const response = await fetch('data/blog-posts.json');
        if (!response.ok) {
            throw new Error('Blog data not found');
        }
        return await response.json();
    } catch (error) {
        console.error('Error loading blog posts:', error);
        return [];
    }
}

// Load mentor interactions data
async function loadMentorInteractions() {
    try {
        const response = await fetch('data/mentor-interactions.json');
        if (!response.ok) {
            throw new Error('Mentor interactions data not found');
        }
        return await response.json();
    } catch (error) {
        console.error('Error loading mentor interactions:', error);
        return [];
    }
}

// Load weekly updates
async function loadWeeklyUpdates() {
    try {
        const response = await fetch('data/weekly-updates.json');
        if (!response.ok) {
            throw new Error('Weekly updates not found');
        }
        return await response.json();
    } catch (error) {
        console.error('Error loading weekly updates:', error);
        return [];
    }
}

// Load milestones
async function loadMilestones() {
    try {
        const response = await fetch('data/milestones.json');
        if (!response.ok) {
            throw new Error('Milestones not found');
        }
        return await response.json();
    } catch (error) {
        console.error('Error loading milestones:', error);
        return [];
    }
}

// Render header
function renderHeader(config) {
    document.getElementById('student-name').textContent = config.student.name;
    document.getElementById('student-bio').textContent = config.student.bio;
    document.getElementById('student-avatar').src = config.student.avatar;
    document.getElementById('student-avatar').alt = config.student.name;

    const socialLinks = document.getElementById('social-links');
    socialLinks.innerHTML = '';

    // Tailwind classes for social links
    const linkClass = "text-gray-400 hover:text-primary transition-colors duration-200 text-xl";

    if (config.student.github) {
        socialLinks.innerHTML += `
            <a href="${config.student.github}" target="_blank" class="${linkClass}">
                <i class="fab fa-github"></i>
            </a>
        `;
    }

    if (config.student.linkedin) {
        socialLinks.innerHTML += `
            <a href="${config.student.linkedin}" target="_blank" class="${linkClass}">
                <i class="fab fa-linkedin"></i>
            </a>
        `;
    }

    if (config.student.email) {
        socialLinks.innerHTML += `
            <a href="mailto:${config.student.email}" class="${linkClass}">
                <i class="fas fa-envelope"></i>
            </a>
        `;
    }

    // Hardcoded UI strings for sections
    const sectionTitles = {
        project: "GSoC Project",
        github: "GitHub Contributions",
        slack: "Community Participation",
        mentors: "Mentor Interactions",
        updates: "Weekly Updates",
        milestones: "Milestones & Achievements"
    };

    const githubStatsLabels = {
        commits: "Commits",
        pullRequests: "Pull Requests",
        issues: "Issues",
        reviews: "Reviews"
    };

    const slackDescription = "Active in organization communication channels";
    const slackJoinButton = "Join Slack Workspace";
    const footerText = "GSoC Student Dashboard | Generated automatically via GitHub Actions";

    // Apply hardcoded UI strings
    document.title = "GSoC Student Dashboard"; // Page Title

    // const headerTitle = document.querySelector('header h1');
    // if (headerTitle) headerTitle.textContent = "GSoC Student Dashboard";

    const headerSubtitle = document.getElementById('student-bio');
    if (headerSubtitle && headerSubtitle.textContent === "GSoC Contributor") {
        headerSubtitle.textContent = "GSoC Contributor";
    }

    const elProject = document.getElementById('section-title-project');
    if (elProject) elProject.innerHTML = `<i class="fas fa-project-diagram mr-2"></i> ${sectionTitles.project}`;

    const elGithub = document.getElementById('section-title-github');
    if (elGithub) elGithub.innerHTML = `<i class="fab fa-github mr-2"></i> ${sectionTitles.github}`;

    document.querySelectorAll('.stat-label').forEach((el, index) => {
        const labels = [
            githubStatsLabels.commits,
            githubStatsLabels.pullRequests,
            githubStatsLabels.issues,
            githubStatsLabels.reviews
        ];
        if (labels[index]) el.textContent = labels[index];
    });

    const elSlack = document.getElementById('section-title-slack');
    if (elSlack) elSlack.innerHTML = `<i class="fab fa-slack mr-2"></i> ${sectionTitles.slack}`;

    const descElSlack = document.querySelector('.slack-description');
    if (descElSlack) descElSlack.textContent = slackDescription;

    const btnElSlack = document.getElementById('slack-link');
    if (btnElSlack) btnElSlack.innerHTML = `<i class="fab fa-slack mr-2"></i> ${slackJoinButton}`;

    const elMentors = document.getElementById('section-title-mentors');
    if (elMentors) elMentors.innerHTML = `<i class="fas fa-user-tie mr-2"></i> ${sectionTitles.mentors}`;

    const elUpdates = document.getElementById('section-title-updates');
    if (elUpdates) elUpdates.innerHTML = `<i class="fas fa-calendar-week mr-2"></i> ${sectionTitles.updates}`;

    const elMilestones = document.getElementById('section-title-milestones');
    if (elMilestones) elMilestones.innerHTML = `<i class="fas fa-trophy mr-2"></i> ${sectionTitles.milestones}`;

    const footerTextEl = document.getElementById('footer-text');
    if (footerTextEl) footerTextEl.textContent = footerText;
}

// Render project info
function renderProjectInfo(config) {
    document.getElementById('project-title').textContent = config.project.title;
    document.getElementById('project-description').textContent = config.project.description;

    document.getElementById('organization').innerHTML = `
        <i class="fas fa-building mr-2 text-white/80"></i> Organization: ${config.project.organization}
    `;
    document.getElementById('timeline').innerHTML = `
        <i class="fas fa-calendar mr-2 text-white/80"></i> Timeline: ${config.project.timeline}
    `;
}

// Render GitHub stats
function renderGitHubStats(data) {
    document.getElementById('total-commits').textContent = data.stats.commits || 0;
    document.getElementById('total-prs').textContent = data.stats.pullRequests || 0;
    document.getElementById('total-issues').textContent = data.stats.issues || 0;
    document.getElementById('total-reviews').textContent = data.stats.reviews || 0;

    const contributionList = document.getElementById('contribution-list');
    if (data.contributions && data.contributions.length > 0) {
        contributionList.innerHTML = data.contributions.map(contrib => `
            <div class="p-4 border border-gray-100 dark:border-gray-700 rounded-lg hover:shadow-sm transition-shadow bg-white dark:bg-gray-700/50">
                <h4 class="font-semibold text-gray-800 dark:text-gray-200 mb-1">${contrib.title}</h4>
                <p class="text-sm text-gray-600 dark:text-gray-400 mb-2">${contrib.description}</p>
                <div class="text-xs text-gray-500 dark:text-gray-500 flex items-center">
                    <i class="fas fa-clock mr-1"></i> ${formatDate(contrib.date)}
                    ${contrib.url ? `<span class="mx-2">|</span> <a href="${contrib.url}" target="_blank" class="text-primary hover:text-primary-dark">View on GitHub</a>` : ''}
                </div>
            </div>
        `).join('');
    } else {
        contributionList.innerHTML = '<p class="text-gray-500 Italic">No contributions data available yet. The GitHub Actions workflow will populate this automatically.</p>';
    }
}

// Render Slack info
function renderSlackInfo(config) {
    const slackChannels = document.getElementById('slack-channels');
    const slackLink = document.getElementById('slack-link');

    if (config.slack.channels && config.slack.channels.length > 0) {
        slackChannels.innerHTML = config.slack.channels.map(channel => `
            <div class="flex items-center gap-2 p-2 bg-gray-50 dark:bg-gray-700/50 rounded-md text-gray-700 dark:text-gray-300">
                <i class="fas fa-hashtag text-gray-400 dark:text-gray-500"></i>
                <span>${channel}</span>
            </div>
        `).join('');
    } else {
        slackChannels.innerHTML = '<p class="text-gray-500 italic">Configure your Slack channels in config.json</p>';
    }

    if (config.slack.workspaceUrl) {
        slackLink.href = config.slack.workspaceUrl;
        slackLink.classList.remove('hidden');
        slackLink.style.display = 'inline-block'; // Ensure it's visible if hidden via CSS initially
    }
}

// Render mentor info
function renderMentorInfo(mentorData) {
    if (!mentorData) {
        console.warn('renderMentorInfo: missing mentorData');
        return;
    }

    const mentorDetails = document.getElementById('mentor-details');
    const feedbackList = document.getElementById('feedback-list');

    if (!mentorDetails || !feedbackList) {
        console.warn('renderMentorInfo: required DOM elements missing');
        return;
    }

    // data/mentor-interactions.json now contains { mentors: [...], interactions: [...] }
    const mentors = mentorData.mentors || [];
    const interactions = mentorData.interactions || [];

    // Removed unused leadMentorTitle and coMentorTitle variables

    if (mentors.length === 0) {
        mentorDetails.innerHTML =
            '<p class="text-gray-500 italic">Mentor information not configured in data/mentor-interactions.json.</p>';
    } else {
        mentorDetails.innerHTML = mentors
            .map((mentor) => {
                return `
                <div class="flex items-center gap-4 p-4 border border-gray-100 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-700/50">
                    <img src="${mentor.avatar || 'assets/images/sample-mentor.svg'}"
                         alt="${mentor.name}"
                         class="w-12 h-12 rounded-full object-cover border-2 border-gray-200 dark:border-gray-600">
                    <div class="flex-1 min-w-0">
                        <h3 class="font-medium text-gray-900 dark:text-white truncate">${mentor.name}</h3>
                        <p class="text-sm text-gray-500 dark:text-gray-400">${mentor.role || 'Mentor'}</p>
                        ${mentor.email ? `<p class="text-xs text-gray-400 dark:text-gray-500 mt-1 flex items-center"><i class="fas fa-envelope mr-1"></i> ${mentor.email}</p>` : ''}
                        ${mentor.github ? `<p class="text-xs text-primary mt-1"><a href="${mentor.github}" target="_blank" class="hover:underline flex items-center"><i class="fab fa-github mr-1"></i> GitHub</a></p>` : ''}
                    </div>
                </div>
                `;
            })
            .join('');
    }

    if (interactions.length > 0) {
        feedbackList.innerHTML = interactions
            .map((item) => {
                const dateText = item.date ? formatDate(item.date) : '';
                return `
                <div class="p-4 bg-gray-50 dark:bg-gray-700/30 rounded-lg border border-gray-100 dark:border-gray-700">
                    <div class="flex justify-between items-center mb-2">
                        <strong class="text-gray-800 dark:text-gray-200 font-medium">${item.from}</strong>
                        <span class="text-xs text-gray-500 dark:text-gray-500">${dateText}</span>
                    </div>
                    <div class="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">${item.content || ''}</div>
                </div>
                `;
            })
            .join('');
    } else {
        feedbackList.innerHTML =
            '<p class="text-gray-500 italic">No interactions logged yet. Add them to data/mentor-interactions.json</p>';
    }
}

// Render blog posts
function renderBlogPosts(posts) {
    const blogList = document.getElementById('blog-posts');
    const blogLink = document.getElementById('blog-link');

    // Store posts globally or in closure for access
    window.blogPostsData = posts;

    if (posts && posts.length > 0) {
        blogList.innerHTML = posts.map((post, index) => `
            <div class="p-4 border border-gray-100 dark:border-gray-700 rounded-lg hover:shadow-md transition-shadow bg-white dark:bg-gray-700/50 group cursor-pointer" onclick="openBlogModal(${index})">
                <h3 class="font-semibold text-lg text-gray-800 dark:text-white group-hover:text-primary transition-colors mb-2">${post.title}</h3>
                <div class="text-xs text-gray-500 dark:text-gray-400 mb-3 flex items-center gap-2">
                    <span><i class="fas fa-calendar mr-1"></i> ${formatDate(post.date)}</span>
                    ${post.readTime ? `<span>|</span> <span><i class="fas fa-clock mr-1"></i> ${post.readTime}</span>` : ''}
                </div>
                <p class="text-gray-600 dark:text-gray-300 text-sm line-clamp-3">${post.excerpt}</p>
            </div>
        `).join('');
    } else {
        blogList.innerHTML = '<p class="text-gray-500 italic">No blog posts yet. Add your posts to data/blog-posts.json</p>';
    }
}

// Blog Modal Logic
function openBlogModal(index) {
    const post = window.blogPostsData[index];
    if (!post) return;

    const modal = document.getElementById('blog-modal');
    const title = document.getElementById('blog-modal-title');
    const date = document.getElementById('blog-modal-date');
    const content = document.getElementById('blog-modal-content');

    title.textContent = post.title;
    date.innerHTML = `<i class="fas fa-calendar mr-1"></i> ${formatDate(post.date)}`;
    content.innerHTML = post.content || `<p>${post.excerpt}</p><p class="italic text-gray-500 mt-4">(No full content available)</p>`;

    modal.classList.remove('hidden');
    // Prevent body scroll
    document.body.style.overflow = 'hidden';
}

function closeBlogModal() {
    const modal = document.getElementById('blog-modal');
    modal.classList.add('hidden');
    // Restore body scroll
    document.body.style.overflow = 'auto';
}

// Event listeners for modal
document.addEventListener('DOMContentLoaded', () => {
    const modal = document.getElementById('blog-modal');
    const closeBtn = document.getElementById('blog-modal-close');

    if (closeBtn) {
        closeBtn.addEventListener('click', closeBlogModal);
    }

    if (modal) {
        modal.addEventListener('click', (e) => {
            if (e.target === modal) {
                closeBlogModal();
            }
        });
    }

    // Close on Escape key
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && !modal.classList.contains('hidden')) {
            closeBlogModal();
        }
    });
});

// Render weekly updates
function renderWeeklyUpdates(updates) {
    const timeline = document.getElementById('weekly-updates');
    if (updates && updates.length > 0) {
        timeline.innerHTML = updates.map((update, index) => `
            <div class="pl-4 border-l-2 border-primary relative py-2 ml-2">
                <div class="absolute w-3 h-3 bg-primary rounded-full -left-[7px] top-3"></div>
                <h4 class="font-semibold text-gray-800 dark:text-gray-200 text-lg">${update.title}</h4>
                <p class="text-gray-600 dark:text-gray-400 mt-1 mb-2">${update.summary}</p>
                <div class="text-xs text-gray-400 dark:text-gray-500 flex items-center">
                    <i class="fas fa-calendar mr-1"></i> ${formatDate(update.date)}
                </div>
            </div>
        `).join('');
    } else {
        timeline.innerHTML = '<p class="text-gray-500 italic">No weekly updates yet. Add your updates to data/weekly-updates.json</p>';
    }
}

// Render milestones
function renderMilestones(milestones) {
    const milestoneList = document.getElementById('milestones');
    if (milestones && milestones.length > 0) {
        milestoneList.innerHTML = milestones.map(milestone => `
            <div class="flex gap-4 p-4 border border-gray-100 dark:border-gray-700 rounded-lg bg-gray-50 dark:bg-gray-700/50 items-start">
                <div class="w-10 h-10 rounded-full bg-yellow-100 dark:bg-yellow-900/30 flex items-center justify-center text-yellow-600 dark:text-yellow-500 flex-shrink-0">
                    <i class="fas fa-${milestone.icon || 'trophy'}"></i>
                </div>
                <div class="flex-1">
                    <h4 class="font-semibold text-gray-800 dark:text-gray-200">${milestone.title}</h4>
                    <p class="text-sm text-gray-600 dark:text-gray-400 mt-1 mb-2">${milestone.description}</p>
                    <div class="text-xs text-gray-400 dark:text-gray-500 flex items-center">
                        <i class="fas fa-calendar mr-1"></i> ${formatDate(milestone.date)}
                    </div>
                </div>
            </div>
        `).join('');
    } else {
        milestoneList.innerHTML = '<p class="text-gray-500 italic">No milestones yet. Add your achievements to data/milestones.json</p>';
    }
}

// Format date helper
function formatDate(dateString) {
    const date = new Date(dateString);
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    return date.toLocaleDateString('en-US', options);
}

// Update last updated timestamp
function updateLastUpdated() {
    const lastUpdated = document.getElementById('last-updated');
    if (lastUpdated) lastUpdated.textContent = new Date().toLocaleString();
}

// Theme Logic (No localStorage, System Default)
function initTheme() {
    // Check system preference
    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
        document.documentElement.classList.add('dark');
    }
}

function toggleTheme() {
    document.documentElement.classList.toggle('dark');
}

// Initialize dashboard
async function initDashboard() {
    try {
        initTheme(); // Initialize theme

        // Theme toggle listener
        const themeBtn = document.getElementById('theme-toggle');
        if (themeBtn) {
            themeBtn.addEventListener('click', toggleTheme);
        }

        // Load all data
        const config = await loadConfig();

        // Render all sections
        renderHeader(config);
        renderProjectInfo(config);
        const githubData = await loadGitHubData(config);
        renderGitHubStats(githubData);
        renderSlackInfo(config);
        const blogPosts = await loadBlogPosts();
        renderBlogPosts(blogPosts);
        const mentorData = await loadMentorInteractions();
        renderMentorInfo(mentorData);
        const weeklyUpdates = await loadWeeklyUpdates();
        renderWeeklyUpdates(weeklyUpdates);
        const milestones = await loadMilestones();
        renderMilestones(milestones);
        updateLastUpdated();
    } catch (error) {
        console.error('Error initializing dashboard:', error);
    }
}

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', initDashboard);
